son

diff --git a/helm-charts/test-containers/templates/files/cassandra/cassandra-init-scripts.yaml b/helm-charts/test-containers/templates/files/cassandra/cassandra-init-scripts.yaml
--- a/helm-charts/test-containers/templates/files/cassandra/cassandra-init-scripts.yaml
+++ b/helm-charts/test-containers/templates/files/cassandra/cassandra-init-scripts.yaml
@@ -39,6 +39,11 @@ data:
       echo "{{ trimSuffix "\n" .loadScript }}" | sed "s|\$FILE_PATH|${FILE_PATH}|g" | cqlsh -u $CASSANDRA_USER -p $CASSANDRA_PASSWORD
       #cqlsh -u cassandra -p cassandra -e "COPY test.title_ratings (tconst, averageRating, numVotes) FROM '/tmp/title.ratings.tsv' WITH DELIMITER='	' AND HEADER=TRUE AND NULL='\N';"
 
+      if [ $? -ne 0 ]; then
+      echo "Data import failed. Please check the logs for more details."
+      exit 1
+      fi
+
       ls -al /tmp
     {{- end }}
     {{- end }}
